[pytest]

python_files = test_*.py

python_classes = Test*

python_functions = test_*

markers =
    smoke: Smoke Test Suite
    regression: Regression Test Suite

addopts =
    -v
    --html=reports/report.html
    --self-contained-html